services:
  simulator-mqtt:
    container_name: mqttsim
    image: nsubrahm/mqttsim:latest
    env_file:
      - mqtt.env
    networks:
      - mitra

networks:
  mitra:
    external: true
    name: mitra