version: '3.5'

services:
  simulator-ksub:
    container_name: simulator-ksub
    image: nsubrahm/simulator-ksub:v0.0.0
    env_file:
      - ksub.env
      - sasl-auth.env
    networks:
      - kafkastreams-network

networks:
  kafkastreams-network:
    name: ks