version: '3.5'

services:
  simulator-rest:
    container_name: simulator-rest
    image: nsubrahm/simulator-rest:v0.0.0
    env_file:
      - rest.env
    networks:
      - core

networks:
  core:
    name: core
