version: '3.5'

services:
  simulator-rest:
    container_name: restsim
    image: nsubrahm/restsim:wimera
    env_file:
      - rest.env
    networks:
      - broker

networks:
  broker:
    external: true
    name: broker