services:
  simulator-rest:
    container_name: restsim
    image: nsubrahm/restsim:main
    env_file:
      - rest.env
    networks:
      - broker

networks:
  broker:
    external: true
    name: broker