services:
  simulator-rest:
    container_name: restsim
    image: nsubrahm/restsim:latest
    env_file:
      - rest.env
    networks:
      - mitra

networks:
  broker:
    external: true
    name: mitra